# Generated by Django 4.2.6 on 2023-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(default="image/user-logo.png", upload_to="image"),
        ),
    ]
