# Generated by Django 4.1.4 on 2023-03-18 05:50

import contract.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Contract',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Leave_and_License', max_length=255)),
                ('agreement_valid_start_date', models.DateField(default=datetime.date.today)),
                ('agreement_valid_end_date', models.DateField(blank=True, null=True)),
                ('locking_period', models.DateField(blank=True, editable=False, null=True)),
                ('agreement_valid_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_rental_user_aggreement_valid_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_rental_user_ghar_patti_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_start_date', models.DateField(default=datetime.date.today)),
                ('ghar_patti_end_date', models.DateField(blank=True, null=True)),
                ('gala', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gala_rental_contract_detail', to='warehouse.gala')),
                ('owner', models.ForeignKey(default=contract.models.get_main_owner, on_delete=django.db.models.deletion.CASCADE, related_name='get_investor_contract', to='account.userandinvestor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract', to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Contract With Rental',
            },
            bases=('contract.contract',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Saledeed', max_length=255)),
                ('agreement_valid_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_investor_user_aggreement_valid_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_investor_user_ghar_patti_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_start_date', models.DateField(default=datetime.date.today)),
                ('ghar_patti_end_date', models.DateField(blank=True, null=True)),
                ('gala', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gala_investor_contract_detail', to='warehouse.gala')),
                ('owner', models.ForeignKey(default=contract.models.get_main_owner, on_delete=django.db.models.deletion.CASCADE, related_name='get_owner_contract', to='account.owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contract', to='account.investor')),
            ],
            options={
                'verbose_name_plural': 'Contract With Investor',
            },
            bases=('contract.contract',),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Development', max_length=255)),
                ('agreement_valid_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_farmer_user_aggreement_valid_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_farmer_user_ghar_patti_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ghar_patti_start_date', models.DateField(default=datetime.date.today)),
                ('ghar_patti_end_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(default=contract.models.get_main_owner, on_delete=django.db.models.deletion.CASCADE, related_name='get_farmer_contract', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_contract', to='account.farmer')),
                ('warehouse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_warehouse_detail', to='warehouse.property')),
            ],
            options={
                'verbose_name_plural': 'Contract With Farmer',
            },
            bases=('contract.contract',),
        ),
    ]
