# Generated by Django 4.1.4 on 2023-03-20 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='locking_period',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
