# Generated by Django 4.1.4 on 2023-07-13 07:35

import contract.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('account', '0001_initial'),
        ('contract', '0002_alter_rental_locking_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='locking_period',
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('renew_agreement_type', models.CharField(default='Leave_and_License', max_length=255)),
                ('renew_agreement_valid_start_date', models.DateField(default=datetime.date.today)),
                ('renew_agreement_valid_end_date', models.DateField(blank=True, null=True)),
                ('renew_agreement_valid_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_rental_user_history_aggreement_valid_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('renew_ghar_patti_doc', models.FileField(blank=True, max_length=255, null=True, upload_to=contract.models.upload_to_rental_user_history_ghar_patti_doc, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('renew_ghar_patti_start_date', models.DateField(default=datetime.date.today)),
                ('renew_ghar_patti_end_date', models.DateField(blank=True, null=True)),
                ('reason_text', models.TextField(default='')),
                ('is_reNewed', models.BooleanField(default=False)),
                ('is_leaved', models.BooleanField(default=False)),
                ('renew_gala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gala_contract_history', to='warehouse.gala')),
                ('renew_owner', models.ForeignKey(default=contract.models.get_main_owner, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_contract_history', to='account.userandinvestor')),
                ('renew_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contract_history', to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Contract History',
            },
            bases=('contract.contract',),
        ),
    ]
