services:
  backend:
    image: mayank1412/omkar-backend     
    ports:
      - "9000:9000"
    volumes:
      - ./../backend:/backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"

  frontend:
    image: mayank1412/omkar-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: npm start
