# Generated by Django 4.1.4 on 2023-02-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalnotification',
            name='gala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.gala'),
        ),
        migrations.AddField(
            model_name='rentalnotification',
            name='status',
            field=models.CharField(choices=[('Leave_Gala', 'Leave_Gala'), ('Service_Gala', 'Service_Gala')], default='', max_length=50),
        ),
    ]
