# Generated by Django 4.1.4 on 2023-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rentalnotification_gala_rentalnotification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalnotification',
            options={'verbose_name_plural': 'Rental Notification'},
        ),
        migrations.AddField(
            model_name='rentalnotification',
            name='sub_service_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
