# Generated by Django 4.1.4 on 2023-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_rentalnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalnotification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
