# Generated by Django 4.1.4 on 2023-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rentalnotification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalnotification',
            name='status',
            field=models.CharField(choices=[('Leave_Gala', 'Leave_Gala'), ('Service_Gala', 'Service_Gala'), ('Renew_Gala', 'Renew_Gala')], default='', max_length=50),
        ),
    ]
