# Generated by Django 4.1.4 on 2023-01-30 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Company',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(default='', max_length=256)),
                ('property_type', models.CharField(choices=[('PEB', 'Peb'), ('COLD_STORAGE', 'Cold Storage'), ('RCC', 'Rcc'), ('SHED', 'Shed'), ('OTHER', 'Other')], max_length=200, verbose_name='warehouse type')),
                ('property_survey_number', models.CharField(default=1, max_length=36, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('is_allotted_to_farmer', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_properties', to='warehouse.company')),
            ],
            options={
                'verbose_name_plural': 'Property',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Gala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gala_number', models.CharField(default=1, max_length=200, unique=True)),
                ('gala_area_size', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gala_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_allotted', models.BooleanField(default=False)),
                ('is_allotted_to_rental', models.BooleanField(default=False)),
                ('is_allotted_to_farmer', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_gala', to='warehouse.property')),
            ],
            options={
                'verbose_name_plural': 'Gala',
                'ordering': ('-created_at',),
            },
        ),
    ]
