# Generated by Django 4.1.4 on 2023-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gala',
            name='gala_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
