# Generated by Django 4.1.4 on 2023-01-30 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import service.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.gala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Repair Request',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='sub service name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name_plural': 'Sub Service',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(blank=True, max_length=11, null=True)),
                ('service_request_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In-progress ', 'In-progress'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', max_length=50, verbose_name='status')),
                ('description', models.TextField(blank=True, null=True)),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.gala')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Service Request',
            },
        ),
        migrations.CreateModel(
            name='RepairRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=service.models.upload_to_request_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('repair_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.repairrequest')),
            ],
            options={
                'verbose_name_plural': 'Repair Request Image',
            },
        ),
        migrations.CreateModel(
            name='LeaveGalaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('gala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.gala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rental')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=service.models.upload_to_service_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
            options={
                'verbose_name_plural': 'Service Request Image',
            },
        ),
    ]
