# Generated by Django 4.1.4 on 2023-02-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_delete_repairrequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_images', to='service.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In-progress ', 'In-progress'), ('Completed', 'Completed'), ('Reject', 'Reject')], default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
