# Generated by Django 4.1.4 on 2023-02-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_delete_repairrequestimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='service_request',
            new_name='sub_service',
        ),
    ]
