# Generated by Django 4.1.4 on 2023-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_image_service_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavegalarequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leavegalarequest',
            name='service_uid',
        ),
        migrations.AddField(
            model_name='leavegalarequest',
            name='reason_for_leaving',
            field=models.TextField(default=''),
        ),
    ]
