# Generated by Django 4.1.4 on 2023-02-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_service_request_servicerequest_sub_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='sub_service',
            new_name='request_sub_service',
        ),
    ]
