# Generated by Django 4.1.4 on 2023-02-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('service', '0005_remove_leavegalarequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavegalarequest',
            name='gala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_gala_leave_request', to='warehouse.gala'),
        ),
        migrations.AlterField(
            model_name='leavegalarequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leave_request', to='account.rental'),
        ),
    ]
