# Generated by Django 4.1.4 on 2023-02-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('service', '0006_alter_leavegalarequest_gala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavegalarequest',
            name='gala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gala_leave_request', to='warehouse.gala'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In-progress', 'In-progress'), ('Completed', 'Completed'), ('Reject', 'Reject')], default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
