# Generated by Django 4.1.4 on 2023-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_leavegalarequest_gala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegalarequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
