# Generated by Django 4.1.4 on 2023-02-27 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_leavegalarequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegalarequest',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
