# Generated by Django 4.1.4 on 2023-02-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_sub_service_servicerequest_request_sub_service'),
        ('service', '0009_leavegalarequest_uid'),
    ]

    operations = [
    ]
