# Generated by Django 4.1.4 on 2023-03-20 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('warehouse', '0003_alter_property_property_survey_number'),
        ('service', '0010_merge_20230228_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewGalaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('renew_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=50, verbose_name='status')),
                ('renew_created_at', models.DateTimeField(auto_now_add=True)),
                ('renew_updated_at', models.DateTimeField(auto_now=True)),
                ('renew_gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gala_renew_request', to='warehouse.gala')),
                ('renew_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_renew_request', to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Renew Gala Request',
            },
        ),
    ]
