# Generated by Django 4.1.4 on 2023-07-13 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('25d10352-95f8-48ab-b918-e9e9fb581d0d')),
        ),
    ]
