# Generated by Django 4.1.4 on 2023-07-13 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0002_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6dd18301-fb11-4020-b75d-7b457b2a8de7')),
        ),
    ]
