# Generated by Django 4.1.4 on 2023-09-25 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_authentication", "0003_alter_tokenauthentication_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauthentication",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a41c48f7-33d1-4272-b6f7-2900ad7496c9")
            ),
        ),
    ]
