# Generated by Django 4.2.6 on 2023-10-30 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_authentication", "0004_alter_tokenauthentication_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauthentication",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("fa16126e-8598-4d78-9905-c78e6d82d9fb")
            ),
        ),
    ]
