# Generated by Django 4.2.6 on 2023-10-30 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0005_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('68ddb03f-b48f-462f-ae8a-54366dc4f8e3')),
        ),
    ]
