# Generated by Django 4.2.6 on 2023-10-30 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0006_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('050973b2-72cf-4cda-8de4-d1525b568873')),
        ),
    ]
