# Generated by Django 4.2.6 on 2023-10-30 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0007_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8b2758ca-58d9-4110-aa9b-6b5b4b39cc7e')),
        ),
    ]
