# Generated by Django 4.2.6 on 2023-10-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0009_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e0e74ee7-48e4-48d1-a648-3e2d9db2bc7b')),
        ),
    ]
