# Generated by Django 4.2.6 on 2023-10-30 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0010_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('134517fb-6fd4-4338-9e87-4077b81f897c')),
        ),
    ]
