# Generated by Django 4.2.6 on 2023-10-30 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0011_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('14f0fa33-7b85-47ea-906d-cd3bdba7576c')),
        ),
    ]
