# Generated by Django 4.2.6 on 2023-10-31 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0012_alter_tokenauthentication_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenauthentication',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8952e373-7d51-4f3b-81fb-21d99e44f863')),
        ),
    ]
